services:

# INFRASTRUCTURE
  postgres:
    image: postgres:16-alpine
    container_name: herald-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: notification_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - herald-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d notification_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: herald-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - herald-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

# APPLICATIONS
  herald-auth:
    build:
      context: .
      dockerfile: herald-auth/Dockerfile
    container_name: herald-auth
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${AUTH_DB_HOST}
      SPRING_DATASOURCE_USERNAME: ${AUTH_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_DB_PASSWORD}
      SECURITY_INTERNAL_KEY: ${AUTH_INTERNAL_KEY}
      SECURITY_ENCRYPTION_KEY: ${AUTH_ENCRYPTION_KEY}
    networks:
      - herald-net
    depends_on:
      postgres:
        condition: service_healthy

  herald-service:
    build:
      context: .
      dockerfile: herald-service/Dockerfile
    container_name: herald-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SERVICE_DB_HOST}
      SPRING_DATASOURCE_USERNAME: ${SERVICE_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SERVICE_DB_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      TELEGRAM_CONFIG_TOKEN: ${TELEGRAM_CONFIG_TOKEN}
      SECURITY_INTERNAL_KEY: ${SERVICE_SECURITY_INTERNAL_KEY}
      SECURITY_ENCRYPTION_KEY : ${SERVICE_SECURITY_ENCRYPTION_KEY}
    networks:
      - herald-net
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  herald-scheduler:
    build:
      context: .
      dockerfile: herald-scheduler/Dockerfile
    container_name: herald-scheduler
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SCHEDULER_DB_HOST}
      SPRING_DATASOURCE_USERNAME: ${SCHEDULER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SCHEDULER_DB_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      SECURITY_INTERNAL_KEY: ${SCHEDULER_SECURITY_INTERNAL_KEY}
    networks:
      - herald-net
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  herald-gateway:
    build:
      context: .
      dockerfile: herald-gateway/Dockerfile
    container_name: herald-gateway
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Overrides application.yaml configuration
      AUTH_INTERNAL_KEY: ${AUTH_INTERNAL_KEY}
    ports:
      - "8080:8080"
    networks:
      - herald-net
    depends_on:
      herald-auth:
        condition: service_started

# VOLUMES
volumes:
  postgres-data:
  rabbitmq-data:

# NETWORKS
networks:
  herald-net:
    driver: bridge

