spring:
  application:
    name: herald-service

  datasource:
    url: ""
    username: ""
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    host: localhost
    port: 5672
    username: ""
    password: ""

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false

server:
  port: 8083

mail:
  from:
    address: ""
    name: ""

telegram:
  config:
    apiUrl: https://api.telegram.org/bot
    token: ""

security:
  internal-key: ""
  encryption-key: ""